name: bridgestars_launcher
description: A launcher for the Bridgestars unity application.
authors: Bridgestars Technologies Sweden AB

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0 

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #desktop_window: ^0.4.0
  window_manager: ^0.3.2
  provider: ^6.0.5
  http: ^0.13.4
  dio: ^5.1.1
  path_provider: ^2.0.9
  archive: ^3.3.0
  #flutter_easyloading: ^3.0.3
  dart_vlc: ^0.4.0
  #liquid_progress_indicator: ^0.4.0
  #flutter_spinkit: ^5.1.0
  loading_indicator: ^3.0.3
  flutter_platform_alert: ^0.3.0
  bitsdojo_window: ^0.1.1+1
  settings_ui: ^2.0.2
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.2
  squirrel: ^0.1.0
  jinja: ^0.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.6.2



  
flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700


squirrel:
  windows:
    certificateFile: "~/Desktop/certs/certificate.pfx"
    # overrideSigningParameters: "bar"
    loadingGif: "vendor/loading.gif"
    appIcon: "vendor/app_icon.ico"
    # uninstallIconPngUrl: "vendor/app_icon.ico"
    appFriendlyName: "Bridgestars"
    appDescription: "The Bridgestars App"
    setupIcon: "vendor/app_icon.ico"
    releaseDirectory: "release/windows"
    releaseUrl: "https://bridgestars-static-host.s3.eu-north-1.amazonaws.com/launcher"
    buildEnterpriseMsiPackage: false
    dontBuildDeltas: false 


msix_config:
  display_name: Bridgestars
  publisher_display_name: Bridgestars Technologies
  publisher: CN=7C741E7A-7CEB-4D0A-A8E3-90483C44E39D
  identity_name: BridgestarsTechnologies.bridgestarstemp
  msix_version: 1.0.0.0
  logo_path: .\assets\logo.jpg
  start_menu_icon_path: .\assets\logo.jpg
  tile_icon_path: .\assets\logo.jpg
  icons_background_color: '#000000'
  store: true
  capabilities: internetClient, location, microphone, webcam